output "config_yaml" {
  description = "Paste this into scripts/config.yaml"
  value       = <<-YAML
# Auto-generated by terraform/test-resources
source:
  account_id: "${data.aws_caller_identity.source.account_id}"
  region: "${var.source_region}"
  profile: "source-account"

target:
  account_id: "${var.target_account_id}"
  region: "${var.target_region}"
  profile: "target-account"

target_kms_key_arn: "${aws_kms_key.target.arn}"

ec2:
  instance_ids:
    - "${aws_instance.source.id}"

s3:
  buckets:
    - source: "${aws_s3_bucket.source.id}"
      target: "${aws_s3_bucket.target.id}"

rds:
  instances:
    - db_instance_id: "${aws_db_instance.source.identifier}"
      target_instance_class: "db.t3.micro"
      target_subnet_group: ""
  YAML
}

output "source_instance_id" {
  value = aws_instance.source.id
}

output "source_s3_bucket" {
  value = aws_s3_bucket.source.id
}

output "target_s3_bucket" {
  value = aws_s3_bucket.target.id
}

output "source_rds_endpoint" {
  value = aws_db_instance.source.endpoint
}

output "source_rds_identifier" {
  value = aws_db_instance.source.identifier
}

output "target_kms_key_arn" {
  value = aws_kms_key.target.arn
}

output "rds_db_url" {
  description = "DB URL for seed.py (fill in password)"
  value       = "${var.db_engine}://admin:<PASSWORD>@${aws_db_instance.source.endpoint}/migrationtest"
  sensitive   = true
}
